CREATE TABLE payment_intents
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    amount      BIGINT      NOT NULL,
    currency    VARCHAR(3)  NOT NULL,

    status      VARCHAR(40) NOT NULL,

    customer_id BIGINT      NOT NULL,

    description TEXT,
    metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb,

    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_intents_customer
        FOREIGN KEY (customer_id)
            REFERENCES customers (id),

    CONSTRAINT chk_payment_intent_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payment_intent_currency
        CHECK (currency = LOWER(currency) AND LENGTH(currency) = 3),

    CONSTRAINT chk_payment_intent_status
        CHECK (status IN (
                          'REQUIRES_CONFIRMATION',
                          'PROCESSING',
                          'SUCCEEDED',
                          'FAILED',
                          'CANCELLED'
            ))
);

CREATE INDEX idx_payment_intents_customer_id
    ON payment_intents (customer_id);

CREATE INDEX idx_payment_intents_status
    ON payment_intents (status);